# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27525e19b830af3b6db1d982ec924079c046bcba3d5ddff7c351b3f9c50bb0c5123a95fc47bcb73480a9b95ab6f8e81aaf58668980bb82c529b418dcb1844d0a

test:
  secret_key_base: 922c0f2cddc801e7c417758ff5e8277933a08709f6706c18efd4c054ad9f976d8c4c28efd45c176e2533fc3c7f1b6bdb6442308b9230acf51838660342e84790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
